version: '3.4'

services:
  consultest:
    image: ${DOCKER_REGISTRY-}consultest
    build:
      context: .
      dockerfile: ConsulTest/Dockerfile

  consul:
    image: hashicorp/consul
    container_name: consul
    volumes:
      - ./config:/consul/config
      - ./data:/consul/data
      - ./logs:/consul/logs
    command:  consul agent -server -bootstrap-expect=1 -client=0.0.0.0 -ui -bind='{{ GetPrivateIP }}' -data-dir=/consul/data -node=consul-node -datacenter=dc1 -log-level=debug -enable-script-checks=true -config-dir=/consul/config
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge  
